[tool.black]
line-length = 150
target-version = ['py310']

[tool.isort]
profile = "black"
line_length = 150
multi_line_output = 3

[tool.ruff]
line-length = 150

[tool.autopep8]
max_line_length = 150
